stages:
  - image
  - build
  - publish

variables:
  MAVEN_OPTS: "-Xmx2g -XX:ReservedCodeCacheSize=512m"
  JAVA_VERSION_MAJOR: "7"
  LCG_VIEW: "LCG_94"
  LCG_VERSION: "x86_64-centos7-gcc7-opt"

.krb_tgt_template: &krbtgt
  before_script:
    - echo "$KERB_ACCOUNT_PASSWORD" | kinit "$KERB_ACCOUNT_USERNAME@CERN.CH"
    - klist

build-docker-image:
  stage: image
  only:
    - master
  tags:
   - docker-image-build
  script:
    - echo "Building docker image..."
  variables:
    DOCKER_FILE: Dockerfile
    TO: ${CI_REGISTRY_IMAGE}:latest

make-compile-test-step:
  <<: *krbtgt
  stage: build
  script:
    # Export HADOOP_CLASSPATH for test
    - export HADOOP_CLASSPATH=${PWD}/*
    # Make compile and test
    - make all
    # Final rename
    - for f in *.jar; do mv "${f}" "${f%-jar-with-dependencies.jar}.jar"; done
  artifacts:
    paths:
    - "*.jar"
  image: ${CI_REGISTRY_IMAGE}:latest

make-compile-test-step-cvmfs:
  <<: *krbtgt
  tags:
    - cvmfs
  stage: build
  script:
    # Prepare build environment
    - export DIRNAME=/cvmfs/sft.cern.ch/lcg/views/$LCG_VIEW/$LCG_VERSION
    - source $DIRNAME/setup.sh
    - SYS_LIB_PATH="-L${DIRNAME}/lib64"
    - INCLUDE_PATH="${DIRNAME}"
    # Export HADOOP_CLASSPATH for test
    - export HADOOP_CLASSPATH=${PWD}/*
    # Make compile and test
    - MAVEN_FLAGS="-Dsyslibpath=${SYS_LIB_PATH} -Dincludepath=${INCLUDE_PATH}" make all
    # Final rename
    - for f in *.jar; do mv "${f}" "${f%-jar-with-dependencies.jar}-${LCG_VERSION}.jar"; done
  image: ${CI_REGISTRY_IMAGE}:latest
  artifacts:
    paths:
    - "*.jar"

put-s3:
  stage: publish
  script:
    - mkdir public
    - mv *.jar public/
    - yum -y install s3cmd
    - echo "[default]" > $HOME/.s3cfg
    - echo "access_key=" $S3_ACCESS_KEY >> $HOME/.s3cfg
    - echo "secret_key=" $S3_SECRET_KEY >> $HOME/.s3cfg
    - echo "host_base=s3.cern.ch" >> $HOME/.s3cfg
    - echo "host_bucket=%(bucket)s.s3.cern.ch" >> $HOME/.s3cfg
    - cd public
    - s3cmd put *.jar s3://${S3_PATH} --acl-public

