stages:
  - image
  - build
  - publish

variables:
  MAVEN_OPTS: "-Xmx2g -XX:ReservedCodeCacheSize=512m"
  JAVA_VERSION_MAJOR: "7"
  XROOT_CLIENT_VERSION: "4.8.4-c201f"
  LCG_VIEW: "LCG_94"
  LCG_VERSION: "x86_64-centos7-gcc7-opt"

.krb_tgt_template: &krbtgt
  before_script:
    - echo "$KERB_ACCOUNT_PASSWORD" | kinit "$KERB_ACCOUNT_USERNAME@CERN.CH"
    - klist

build-docker-image:
  stage: image
  only:
    - /^docker-.*$/
  tags:
   - docker-image-build
  script:
    - echo "Building docker image..."
  variables:
    DOCKER_FILE: docker/Dockerfile
    TO: ${CI_REGISTRY_IMAGE}/base:latest

make-compile-test-step-centos:
  <<: *krbtgt
  stage: build
  script:
    # Make compile and test
    - make all
    # Final rename
    - for f in *.jar; do mv "${f}" "${f%-jar-with-dependencies.jar}.jar"; done
  artifacts:
    paths:
    - "*.jar"
  image: ${CI_REGISTRY_IMAGE}/base:latest # use docker with all libraries

make-compile-test-step-cvmfs:
  <<: *krbtgt
  tags:
    - cvmfs
  stage: build
  script:
    # Prepare build environment
    - yum install -y which HEP_OSlibs
    - source /cvmfs/sft.cern.ch/lcg/views/$LCG_VIEW/$LCG_VERSION/setup.sh
    - XROOTD_LIB64_PATH="/cvmfs/sft.cern.ch/lcg/releases/xrootd/$XROOT_CLIENT_VERSION/$LCG_VERSION/lib64"
    - XROOTD_INCLUDE_PATH="/cvmfs/sft.cern.ch/lcg/views/$LCG_VIEW/$LCG_VERSION/include/xrootd"
    # Make compile and test
    - MAVEN_FLAGS="-Dxrootd.lib64.path=${XROOTD_LIB64_PATH} -Dxrootd.include.path=${XROOTD_INCLUDE_PATH}" make all
    # Final rename
    - for f in *.jar; do mv "${f}" "${f%-jar-with-dependencies.jar}-${LCG_VERSION}.jar"; done
  artifacts:
    paths:
    - "*.jar"
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base:latest # use clean docker as CVMFS is used

put-s3:
  stage: publish
  only:
    - master
    - qa
  script:
    - mkdir public
    - mv *.jar public/
    - yum -y install s3cmd
    - echo "[default]" > $HOME/.s3cfg
    - echo "access_key=" $S3_ACCESS_KEY >> $HOME/.s3cfg
    - echo "secret_key=" $S3_SECRET_KEY >> $HOME/.s3cfg
    - echo "host_base=s3.cern.ch" >> $HOME/.s3cfg
    - echo "host_bucket=%(bucket)s.s3.cern.ch" >> $HOME/.s3cfg
    - cd public
    - s3cmd put *.jar s3://${S3_PATH} --acl-public

