/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_cern_eos_EOSFileSystem */

#ifndef _Included_ch_cern_eos_EOSFileSystem
#define _Included_ch_cern_eos_EOSFileSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_cern_eos_EOSFileSystem_SHUTDOWN_HOOK_PRIORITY
#define ch_cern_eos_EOSFileSystem_SHUTDOWN_HOOK_PRIORITY 10L
/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    initFileSystem
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_EOSFileSystem_initFileSystem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    getFileStatusS
 * Signature: (JLjava/lang/String;Lorg/apache/hadoop/fs/Path;)Lorg/apache/hadoop/fs/FileStatus;
 */
JNIEXPORT jobject JNICALL Java_ch_cern_eos_EOSFileSystem_getFileStatusS
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    listFileStatusS
 * Signature: (JLjava/lang/String;Lorg/apache/hadoop/fs/Path;)[Lorg/apache/hadoop/fs/FileStatus;
 */
JNIEXPORT jobjectArray JNICALL Java_ch_cern_eos_EOSFileSystem_listFileStatusS
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    Mv
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_EOSFileSystem_Mv
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    Rm
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_EOSFileSystem_Rm
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    MkDir
 * Signature: (JLjava/lang/String;S)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_EOSFileSystem_MkDir
  (JNIEnv *, jobject, jlong, jstring, jshort);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    RmDir
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_EOSFileSystem_RmDir
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    Prepare
 * Signature: (J[Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_EOSFileSystem_Prepare
  (JNIEnv *, jobject, jlong, jobjectArray, jint);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ch_cern_eos_EOSFileSystem_setenv
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_cern_eos_EOSFileSystem_getenv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ch_cern_eos_EOSFileSystem
 * Method:    getErrText
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_cern_eos_EOSFileSystem_getErrText
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
