/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_cern_eos_XrootDBasedClFile */

#ifndef _Included_ch_cern_eos_XrootDBasedClFile
#define _Included_ch_cern_eos_XrootDBasedClFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_cern_eos_XrootDBasedClFile
 * Method:    initFile
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_XrootDBasedClFile_initFile
  (JNIEnv *, jobject);

/*
 * Class:     ch_cern_eos_XrootDBasedClFile
 * Method:    disposeFile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_XrootDBasedClFile_disposeFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_cern_eos_XrootDBasedClFile
 * Method:    openFile
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_XrootDBasedClFile_openFile
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     ch_cern_eos_XrootDBasedClFile
 * Method:    readFile
 * Signature: (JJ[BII)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_XrootDBasedClFile_readFile
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     ch_cern_eos_XrootDBasedClFile
 * Method:    writeFile
 * Signature: (JJ[BII)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_XrootDBasedClFile_writeFile
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     ch_cern_eos_XrootDBasedClFile
 * Method:    syncFile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_XrootDBasedClFile_syncFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_cern_eos_XrootDBasedClFile
 * Method:    closeFile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_cern_eos_XrootDBasedClFile_closeFile
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
